[project]
name = "legal-saathi-document-advisor"
version = "0.1.0"
description = "AI-powered platform for analyzing rental agreements and providing plain-language legal guidance"
authors = [
    {name = "LegalSaathi Team"}
]
dependencies = [
    "flask>=2.3.3",
    "werkzeug>=2.3.7",
    "openai>=1.0.0",
    "groq>=0.4.1",
    "google-generativeai>=0.3.0",
    "google-cloud-translate>=3.12.0",
    "google-cloud-documentai>=2.20.0",
    "google-cloud-language>=2.10.0",
    "google-cloud-speech>=2.21.0",
    "neo4j>=5.0.0",
    "python-dotenv>=1.0.0",
    "pypdf2>=3.0.0",
    "reportlab>=4.0.0",
    "python-docx>=1.1.0",
    "requests>=2.31.0",
]
requires-python = ">=3.9"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
]
