[project]
name = "legal-saathi-document-advisor"
version = "0.1.0"
description = "AI-powered platform for analyzing rental agreements and providing plain-language legal guidance"
authors = [
    {name = "LegalSaathi Team"}
]
dependencies = [
    "flask>=2.3.3",
    "werkzeug>=2.3.7",
    "openai>=1.0.0",
    "groq>=0.4.1",
    "google-generativeai>=0.3.0",
    "neo4j>=5.0.0",
    "python-dotenv>=1.0.0",
]
requires-python = ">=3.9"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
]
